//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hok_Teeth.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Project_M
    {
        public int Cptm_Id { get; set; }
        public int Cptm_CusmId { get; set; }
        public string Cptm_Project_Name { get; set; }
        public string Cptm_Machine { get; set; }
        public string Cptm_Material { get; set; }
        public string Cptm_Tooth_Type { get; set; }
        public string Cptm_Tooth_Src { get; set; }
        public string Cptm_NeckLine_Src { get; set; }
        public System.DateTime Cptm_Create_Datetime { get; set; }
    }
}
