//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hok_Teeth.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_User_M
    {
        public int Cusm_Id { get; set; }
        public string Cusm_Gmail { get; set; }
        public string Cusm_GoogleId { get; set; }
        public string Cusm_Name { get; set; }
        public bool Cusm_Status { get; set; }
        public System.DateTime Cusm_Create_Datetime { get; set; }
        public System.DateTime Cusm_Update_Datetime { get; set; }
    }
}
